name: Make a weekly visit to keep Supabase API active

on:
  schedule:
    - cron: '0 8 * * *'
jobs:
  make-visit:
    runs-on: ubuntu-latest
    steps:
    - name: Send request
      id: solicitude-api
      uses: muhfaris/request-action@v1
      with:
        URL: "https://alvaldes.vercel.app/works"
        method: GET
    - name: Show response status
      run: |
        echo "Estado de la respuesta: ${{ steps.solicitude-api.outputs.response-status }}"
    - name: Show response data
      run: |
        echo "Datos de la respuesta: ${{ steps.solicitude-api.outputs.response-data }}"
