name: Make a weekly visit to keep Supabase API active

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  make-visit:
    runs-on: ubuntu-latest
    steps:
    - name: Send request
      run: |
        RESPONSE=$(curl -s -o output.txt -w "%{http_code}" -X GET "https://alvaldes.vercel.app/works")
        echo "response status: $RESPONSE"
        echo "response data:"
        cat output.txt
